#ifndef JCONFIG_H
#define JCONFIG_H

#define HAVE_PROTOTYPES 1
#define HAVE_UNSIGNED_CHAR 1
#define HAVE_UNSIGNED_SHORT 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define JPEG_INTERNALS
#define RIGHT_SHIFT_IS_UNSIGNED

#endif /* JCONFIG_H */
